language: node_js
node_js:
  - '0.10'
before_install:
  - gem install sass
  - npm install -g grunt-cli
notifications:
  slack:
    rooms:
      - 2bad:V3I2EDTywzZFJSHQuELHphRS#general
    on_success: change
    on_failure: always
  email: false