version: "{build}"

environment:
  matrix:
    - NODE_VERSION: 10
    - NODE_VERSION: 9

cache:
  - node_modules -> package.json

install:
  # Install GraphicsMagick
  - appveyor-retry appveyor DownloadFile http://downloads.sourceforge.net/graphicsmagick/GraphicsMagick-1.3.29-Q16-win64-dll.exe
  - GraphicsMagick-1.3.29-Q16-win64-dll.exe /SP /VERYSILENT /NORESTART /NOICONS /DIR=\gm
  - del GraphicsMagick-1.3.29-Q16-win64-dll.exe
  - set PATH=\gm;%PATH%

  # Update submodule
  - git submodule update --init --recursive

  # Install node and latest version of npm
  - ps: Install-Product node $env:NODE_VERSION x64
  - npm install -g npm@latest

  # Output versions
  - git --version
  - node --version
  - npm --version

  - npm ci

test_script:
  - npm test
  - npm run build

# We don't actually build using MSBuild
build: off