version: 2
jobs:
  setup:
    docker:
      - image: circleci/node:9
    working_directory: ~/kotsu
    steps:
      - checkout
      - attach_workspace:
          at: ~/kotsu
      - run:
          name: Checkout submodules
          command: git submodule update --init --recursive
      - run:
          name: Install latest version of npm
          command: sudo npm install -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install project dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths: node_modules

  test:
    docker:
      - image: circleci/node:9
    working_directory: ~/kotsu
    steps:
      - checkout
      - attach_workspace:
          at: ~/kotsu
      - run:
          name: test
          command: npm run test

  build:
    docker:
      - image: circleci/node:9
    working_directory: ~/kotsu
    steps:
      - checkout
      - attach_workspace:
          at: ~/kotsu
      - run:
          name: build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths: build

  deploy:
    machine: true
    working_directory: ~/kotsu
    steps:
      - checkout
      - attach_workspace:
          at: ~/kotsu
      - run:
          name: Deploy if tests pass and branch is master
          command: |
            ssh-keyscan $SERVER_IP > ~/.ssh/known_hosts
            cat dockerfile.template | envsubst > dockerfile
            tar cvzf app.tgz dockerfile build/
            scp app.tgz core@$SERVER_IP:~/kotsutgz
            scp deploy.sh core@$SERVER_IP:~/deploy.sh
            ssh core@$SERVER_IP chmod +x deploy.sh
            ssh core@$SERVER_IP ./deploy.sh kotsuCIRCLE_SHA1

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - setup
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: master