version: 2
jobs:
  checkout:
    machine: true
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule update --init --recursive
      - save_cache:
          key: repo-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/project

  setup:
    docker:
      - image: circleci/node:9
    steps:
      - run:
          name: Install latest version of npm
          command: sudo npm install -g npm@latest
      - restore_cache:
          keys:
            - repo-cache-{{ .Environment.CIRCLE_SHA1 }}
            - dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install project dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  test:
    docker:
      - image: circleci/node:9
    steps:
      - restore_cache:
          keys:
            - repo-cache-{{ .Environment.CIRCLE_SHA1 }}
            - dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: test
          command: npm run test

  build:
    docker:
      - image: circleci/node:9
    steps:
      - restore_cache:
          keys:
            - repo-cache-{{ .Environment.CIRCLE_SHA1 }}
            - dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: build
          command: npm run build
      - save_cache:
          key: build-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./build

  deploy:
    machine: true
    steps:
      - restore_cache:
          keys:
            - repo-cache-{{ .Environment.CIRCLE_SHA1 }}
            - dependency-cache-{{ checksum "package-lock.json" }}
            - build-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Deploy if tests pass and branch is master
          command: |
            ssh-keyscan $SERVER_IP > ~/.ssh/known_hosts
            cat dockerfile.template | envsubst > dockerfile
            tar cvzf app.tgz dockerfile build/
            scp app.tgz core@$SERVER_IP:~/kotsutgz
            scp deploy.sh core@$SERVER_IP:~/deploy.sh
            ssh core@$SERVER_IP chmod +x deploy.sh
            ssh core@$SERVER_IP ./deploy.sh kotsuCIRCLE_SHA1

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - checkout
      - setup:
          requires:
            - checkout
      - test:
          requires:
            - setup
      - build:
          requires:
            - setup
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: master